[package]
name = "web-push"
description = "Web push notification client with support for http-ece encryption and VAPID authentication."
version = "0.11.0"
authors = ["Julius de Bruijn <julius+github@nauk.io>", "Andrew Ealovega <Andrew@Ealovega.dev>"]
license = "Apache-2.0"
homepage = "https://github.com/pimeys/rust-web-push"
repository = "https://github.com/pimeys/rust-web-push"
documentation = "https://docs.rs/web-push/"
readme = "README.md"
keywords = ["web-push", "http-ece", "vapid"]
categories = ["web-programming", "asynchronous"]
rust-version = "1.87"
edition = "2024"

[features]
default = ["reqwest-client"]
reqwest-client = ["reqwest"]
isahc-client = ["isahc", "futures-lite/futures-io"]

[dependencies]
isahc = { version = "2.0", optional = true }
futures-lite = { version = "2.6", optional = true }
reqwest = { version = "0.13", optional = true }
http = "1.5"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
jsonwebtoken = { version = "11.0", default-features = false, features = ["aws_lc_rs"] }
ece = { version = "2.3", default-features = false }
aws-lc-rs = "1.18"
p256 = "0.14"
chrono = "0.4"
log = "0.4"
async-trait = "0.1"
base64ct = "1.8"

[dev-dependencies]
regex = "1.13"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
